version: "3.8"

services:
    frontend:
        build:
            context: https://github.com/ansabkhaliq/frontend
        ports:
            - "80:80"
        stdin_open: true
        depends_on:
            - backend
    
    backend:
        build:
            context: https://github.com/ansabkhaliq/backend
        ports:
            - "5000:5000"
        env_file:
            - .env.prod
